import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navigation/navbar";
import Sidebar from "./navigation/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col sm:flex-row">
          {/* navigasion */}

          {/* navbar */}
          <Navbar />

          {/* sidebar */}
          <Sidebar />

          {/* children */}
          <div className="w-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
